spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: adeda249321077b1ea78f8f04428cf4f
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname